# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "binary_fixtures"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2014-05-25"
  s.description = "Convenience method for inlining binary data in Rails fixtures"
  s.email = "victor@costan.us"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Gemfile.rails40",
    "Gemfile.rails41",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "binary_fixtures.gemspec",
    "lib/binary_fixtures.rb",
    "lib/binary_fixtures/fixture_helpers.rb",
    "lib/binary_fixtures/patch_rails.rb",
    "lib/binary_fixtures/rails_13022.rb",
    "test/fixtures/attachments.yml",
    "test/fixtures/files/invoice.pdf",
    "test/fixtures/files/ruby.png",
    "test/helper.rb",
    "test/helpers/db_setup.rb",
    "test/helpers/rails.rb",
    "test/migrations/001_create_attachments.rb",
    "test/test_binary_fixtures.rb"
  ]
  s.homepage = "http://github.com/pwnall/binary_fixtures"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Use binary files in Rails fixtures"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 4.1.0"])
      s.add_development_dependency(%q<bundler>, [">= 1.6.2"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<mysql2>, [">= 0.3.16"])
      s.add_development_dependency(%q<pg>, [">= 0.17.1"])
      s.add_development_dependency(%q<sqlite3>, [">= 1.3.9"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7.4"])
    else
      s.add_dependency(%q<rails>, [">= 4.1.0"])
      s.add_dependency(%q<bundler>, [">= 1.6.2"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<mysql2>, [">= 0.3.16"])
      s.add_dependency(%q<pg>, [">= 0.17.1"])
      s.add_dependency(%q<sqlite3>, [">= 1.3.9"])
      s.add_dependency(%q<yard>, [">= 0.8.7.4"])
    end
  else
    s.add_dependency(%q<rails>, [">= 4.1.0"])
    s.add_dependency(%q<bundler>, [">= 1.6.2"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<mysql2>, [">= 0.3.16"])
    s.add_dependency(%q<pg>, [">= 0.17.1"])
    s.add_dependency(%q<sqlite3>, [">= 1.3.9"])
    s.add_dependency(%q<yard>, [">= 0.8.7.4"])
  end
end

